// Writes src/frames.css: the nine-slice pixel frame as one CSS custom property per palette.
// Run `pnpm frames` after editing the rows or colours.
import { writeFileSync } from 'node:fs';

// Rows are 9×9 pixel art: O outline, W wood, H panel highlight, S panel shade, P panel.
const ROWS = [
  '..OOOOO..',
  '.OWWWWWO.',
  'OWHHHHHWO',
  'OWHPPPSWO',
  'OWHPPPSWO',
  'OWHPPPSWO',
  'OWSSSSSWO',
  '.OWWWWWO.',
  '..OOOOO..',
];
const svg = (colors) => {
  const rects = ROWS.flatMap((row, y) =>
    [...row].flatMap((ch, x) =>
      colors[ch] ? [`<rect x='${x}' y='${y}' width='1' height='1' fill='${colors[ch]}'/>`] : [],
    ),
  ).join('');
  const body = `<svg xmlns='http://www.w3.org/2000/svg' width='9' height='9' shape-rendering='crispEdges'>${rects}</svg>`;
  return `url("data:image/svg+xml,${body.replaceAll('#', '%23').replaceAll('<', '%3C').replaceAll('>', '%3E')}")`;
};
const palettes = {
  'day-wood': { O: '#3b2414', W: '#b8702f', H: '#fffbea', S: '#ead39b', P: '#fff3d1' },
  'night-wood': { O: '#05070f', W: '#6b4325', H: '#2d3866', S: '#161c38', P: '#1f2747' },
  'day-paper': { O: '#3b2414', W: '#3d5afe', H: '#ffffff', S: '#dfe5ff', P: '#f4f6ff' },
  'night-paper': { O: '#05070f', W: '#5c74ff', H: '#33407a', S: '#131936', P: '#1b2246' },
};
const vars = Object.entries(palettes).map(([name, colors]) => `  --frame-${name}: ${svg(colors)};`);
writeFileSync(
  new URL('../src/frames.css', import.meta.url),
  `/* generated by scripts/frame-svg.mjs */\n:root {\n${vars.join('\n')}\n}\n`,
);
