// Part and option names from BotHarness's avatar editor (packages/client/src/client/locale.ts),
// so the site and the app call every part the same thing.

export interface AvatarLabels {
  parts: Record<string, string>;
  options: Record<string, string>;
}

export const ZH_AVATAR_LABELS: AvatarLabels = {
  parts: {
    presets: '预设',
    hair: '发型',
    bangs: '刘海',
    sideHair: '侧发',
    backHair: '后发',
    head: '脸型',
    pose: '朝向',
    eyes: '眼睛',
    brows: '眉毛',
    nose: '鼻子',
    mouth: '嘴巴',
    cheeks: '脸颊',
    glasses: '眼镜',
    outfit: '服装',
    accessory: '配饰',
    shape: '五官布局',
    colors: '颜色',
    spacing: '间距',
    height: '高低',
    hairLength: '发长',
    skinColor: '肤色',
    hairColor: '发色',
    eyeColor: '眼睛颜色',
    shirtColor: '衣服颜色',
    shuffle: '随机',
  },
  options: {
    'outfit.tee': 'T 恤',
    'outfit.shirttie': '衬衫领带',
    'outfit.hoodie': '连帽衫',
    'outfit.turtleneck': '高领毛衣',
    'outfit.sailor': '水手服',
    'outfit.blazer': '西装外套',
    'outfit.overalls': '背带裤',
    'pose.front': '正脸',
    'pose.left': '向左 30°',
    'pose.right': '向右 30°',
    'head.round': '圆脸',
    'head.oval': '鹅蛋脸',
    'head.square': '方脸',
    'head.long': '长脸',
    'head.heart': '心形脸',
    'head.vchin': '尖下巴',
    'head.chubby': '圆嘟嘟',
    'head.diamond': '菱形脸',
    'hair.crop': '短发',
    'hair.sweep': '侧分',
    'hair.spiky': '刺猬头',
    'hair.buzz': '寸头',
    'hair.curly': '卷发',
    'hair.mohawk': '莫西干',
    'hair.bob': '齐耳短发',
    'hair.long': '长发',
    'hair.bun': '丸子头',
    'hair.pigtails': '双马尾',
    'hair.afro': '爆炸头',
    'hair.twintails': '长双马尾',
    'hair.drills': '螺旋双马尾',
    'hair.ponytail': '高马尾',
    'hair.sidetail': '侧马尾',
    'hair.hime': '姬发式',
    'hair.odango': '双丸子头',
    'hair.messy': '呆毛乱发',
    'hair.none': '光头',
    'eyes.round': '圆眼',
    'eyes.dot': '豆豆眼',
    'eyes.sparkle': '闪亮眼',
    'eyes.lashes': '睫毛眼',
    'eyes.sleepy': '困倦眼',
    'eyes.happy': '笑眼',
    'eyes.wink': '眨眼',
    'eyes.sharp': '锐利眼',
    'brows.soft': '柔和',
    'brows.thick': '浓眉',
    'brows.raised': '挑眉',
    'brows.angry': '皱眉',
    'brows.worried': '八字眉',
    'brows.none': '无',
    'nose.button': '小鼻',
    'nose.dot': '点鼻',
    'nose.line': '线条鼻',
    'nose.none': '无',
    'mouth.smile': '微笑',
    'mouth.grin': '露齿笑',
    'mouth.open': '张嘴',
    'mouth.flat': '一字嘴',
    'mouth.smirk': '坏笑',
    'mouth.cat': '猫嘴',
    'mouth.tongue': '吐舌',
    'mouth.o': 'O 型嘴',
    'cheeks.blush': '腮红',
    'cheeks.freckles': '雀斑',
    'cheeks.none': '无',
    'glasses.none': '无',
    'glasses.round': '圆框',
    'glasses.square': '方框',
    'glasses.shades': '墨镜',
    'glasses.monocle': '单片镜',
    'accessory.none': '无',
    'accessory.beanie': '毛线帽',
    'accessory.cap': '棒球帽',
    'accessory.headphones': '耳机',
    'accessory.flower': '小花',
    'accessory.bow': '蝴蝶结',
    'accessory.earring': '耳环',
    'accessory.crown': '皇冠',
    'accessory.halo': '光环',
    'accessory.catears': '猫耳',
    'accessory.hairclip': '发夹',
    'accessory.horns': '小角',
    'hair.wavy': '波浪长发',
    'hair.braids': '双麻花辫',
    'hair.wolf': '狼尾层次',
    'hair.ahoge': '呆毛波波头',
    'outfit.dress': '蝴蝶结连衣裙',
    'outfit.kimono': '和服',
    'outfit.cardigan': '开衫',
    'outfit.maid': '女仆装',
    'outfit.jacket': '外套内搭',
    'accessory.beret': '贝雷帽',
    'accessory.ribbon': '大蝴蝶结',
    'accessory.headband': '发箍',
    'accessory.bunnyears': '兔耳',
    'accessory.horseears': '马耳',
    'accessory.flowercrown': '花冠',
    'accessory.witch': '魔女帽',
    'accessory.pins': '交叉发夹',
    'bangs.crop': '短刘海',
    'bangs.bob': '齐刘海',
    'bangs.sweep': '斜刘海',
    'bangs.spiky': '刺猬刘海',
    'bangs.curly': '卷刘海',
    'bangs.messy': '碎刘海',
    'bangs.wolf': '狼尾刘海',
    'bangs.wavy': '波浪刘海',
    'bangs.ahoge': '呆毛',
    'bangs.hime': '姬发式',
    'bangs.buzz': '寸头',
    'bangs.mohawk': '莫西干',
    'bangs.none': '无',
    'sideHair.crop': '短鬓角',
    'sideHair.bun': '贴脸侧发',
    'sideHair.bob': '到下巴',
    'sideHair.long': '长侧发',
    'sideHair.hime': '姬发侧帘',
    'sideHair.curly': '卷侧发',
    'sideHair.braids': '麻花辫',
    'sideHair.none': '无',
    'backHair.none': '无',
    'backHair.bob': '波波',
    'backHair.long': '长发',
    'backHair.wavy': '波浪长发',
    'backHair.wolf': '狼尾',
    'backHair.bun': '丸子',
    'backHair.odango': '双丸子',
    'backHair.pigtails': '低双马尾',
    'backHair.twintails': '双马尾',
    'backHair.drills': '双螺旋卷',
    'backHair.ponytail': '马尾',
    'backHair.sidetail': '侧马尾',
    'backHair.afro': '爆炸头',
  },
};

export const EN_AVATAR_LABELS: AvatarLabels = {
  parts: {
    presets: 'Presets',
    hair: 'Hair',
    bangs: 'Bangs',
    sideHair: 'Side hair',
    backHair: 'Back hair',
    head: 'Face',
    pose: 'Angle',
    eyes: 'Eyes',
    brows: 'Brows',
    nose: 'Nose',
    mouth: 'Mouth',
    cheeks: 'Cheeks',
    glasses: 'Glasses',
    outfit: 'Outfit',
    accessory: 'Accessory',
    shape: 'Layout',
    colors: 'Colors',
    spacing: 'Spacing',
    height: 'Height',
    hairLength: 'Hair length',
    skinColor: 'Skin color',
    hairColor: 'Hair color',
    eyeColor: 'Eye color',
    shirtColor: 'Shirt color',
    shuffle: 'Shuffle',
  },
  options: {
    'outfit.tee': 'T-shirt',
    'outfit.shirttie': 'Shirt and tie',
    'outfit.hoodie': 'Hoodie',
    'outfit.turtleneck': 'Turtleneck',
    'outfit.sailor': 'Sailor collar',
    'outfit.blazer': 'Blazer',
    'outfit.overalls': 'Overalls',
    'pose.front': 'Front',
    'pose.left': 'Left 30°',
    'pose.right': 'Right 30°',
    'head.round': 'Round',
    'head.oval': 'Oval',
    'head.square': 'Square',
    'head.long': 'Long',
    'head.heart': 'Heart',
    'head.vchin': 'Pointed chin',
    'head.chubby': 'Chubby',
    'head.diamond': 'Diamond',
    'hair.crop': 'Crop',
    'hair.sweep': 'Side sweep',
    'hair.spiky': 'Spiky',
    'hair.buzz': 'Buzz cut',
    'hair.curly': 'Curly',
    'hair.mohawk': 'Mohawk',
    'hair.bob': 'Bob',
    'hair.long': 'Long',
    'hair.bun': 'Bun',
    'hair.pigtails': 'Pigtails',
    'hair.afro': 'Afro',
    'hair.twintails': 'Long twin tails',
    'hair.drills': 'Drill twin tails',
    'hair.ponytail': 'High ponytail',
    'hair.sidetail': 'Side ponytail',
    'hair.hime': 'Hime cut',
    'hair.odango': 'Twin buns',
    'hair.messy': 'Messy with ahoge',
    'hair.none': 'Bald',
    'eyes.round': 'Round',
    'eyes.dot': 'Dot',
    'eyes.sparkle': 'Sparkle',
    'eyes.lashes': 'Lashes',
    'eyes.sleepy': 'Sleepy',
    'eyes.happy': 'Happy',
    'eyes.wink': 'Wink',
    'eyes.sharp': 'Sharp',
    'brows.soft': 'Soft',
    'brows.thick': 'Thick',
    'brows.raised': 'Raised',
    'brows.angry': 'Frown',
    'brows.worried': 'Worried',
    'brows.none': 'None',
    'nose.button': 'Button',
    'nose.dot': 'Dot',
    'nose.line': 'Line',
    'nose.none': 'None',
    'mouth.smile': 'Smile',
    'mouth.grin': 'Grin',
    'mouth.open': 'Open',
    'mouth.flat': 'Flat',
    'mouth.smirk': 'Smirk',
    'mouth.cat': 'Cat',
    'mouth.tongue': 'Tongue',
    'mouth.o': 'O',
    'cheeks.blush': 'Blush',
    'cheeks.freckles': 'Freckles',
    'cheeks.none': 'None',
    'glasses.none': 'None',
    'glasses.round': 'Round',
    'glasses.square': 'Square',
    'glasses.shades': 'Shades',
    'glasses.monocle': 'Monocle',
    'accessory.none': 'None',
    'accessory.beanie': 'Beanie',
    'accessory.cap': 'Cap',
    'accessory.headphones': 'Headphones',
    'accessory.flower': 'Flower',
    'accessory.bow': 'Bow',
    'accessory.earring': 'Earring',
    'accessory.crown': 'Crown',
    'accessory.halo': 'Halo',
    'accessory.catears': 'Cat ears',
    'accessory.hairclip': 'Hair clip',
    'accessory.horns': 'Little horns',
    'hair.wavy': 'Long waves',
    'hair.braids': 'Twin braids',
    'hair.wolf': 'Layered wolf cut',
    'hair.ahoge': 'Bob with ahoge',
    'outfit.dress': 'Ribbon dress',
    'outfit.kimono': 'Kimono',
    'outfit.cardigan': 'Cardigan',
    'outfit.maid': 'Maid outfit',
    'outfit.jacket': 'Open jacket',
    'accessory.beret': 'Beret',
    'accessory.ribbon': 'Big ribbon',
    'accessory.headband': 'Headband',
    'accessory.bunnyears': 'Bunny ears',
    'accessory.horseears': 'Horse ears',
    'accessory.flowercrown': 'Flower crown',
    'accessory.witch': 'Witch hat',
    'accessory.pins': 'Crossed hair pins',
    'bangs.crop': 'Short',
    'bangs.bob': 'Blunt',
    'bangs.sweep': 'Side-swept',
    'bangs.spiky': 'Spiky',
    'bangs.curly': 'Curly',
    'bangs.messy': 'Messy',
    'bangs.wolf': 'Wolf',
    'bangs.wavy': 'Wavy',
    'bangs.ahoge': 'Ahoge',
    'bangs.hime': 'Hime cut',
    'bangs.buzz': 'Buzz',
    'bangs.mohawk': 'Mohawk',
    'bangs.none': 'None',
    'sideHair.crop': 'Short sideburns',
    'sideHair.bun': 'Face-framing',
    'sideHair.bob': 'Chin length',
    'sideHair.long': 'Long',
    'sideHair.hime': 'Hime locks',
    'sideHair.curly': 'Curly',
    'sideHair.braids': 'Braids',
    'sideHair.none': 'None',
    'backHair.none': 'None',
    'backHair.bob': 'Bob',
    'backHair.long': 'Long',
    'backHair.wavy': 'Long waves',
    'backHair.wolf': 'Wolf',
    'backHair.bun': 'Bun',
    'backHair.odango': 'Double buns',
    'backHair.pigtails': 'Low pigtails',
    'backHair.twintails': 'Twin tails',
    'backHair.drills': 'Drills',
    'backHair.ponytail': 'Ponytail',
    'backHair.sidetail': 'Side tail',
    'backHair.afro': 'Afro',
  },
};
