import {
  AVATAR_PRESETS,
  DEFAULT_RECIPE,
  detailedRecipe,
  withBuiltInHeadpiece,
  withPieces,
  withSpecies,
  type AvatarHeadpiece,
  type AvatarSpeciesV4,
  type PixelAvatarRecipe,
} from '@botharness/pixel-avatar';

type Fields = Record<string, string | number>;

/**
 * A recipe for `species` with `fields` on top. A headpiece, strand, fur pattern or hair piece
 * color makes it asset version 4, like an edit in the app would.
 */
function preset(
  species: AvatarSpeciesV4,
  fields: Fields,
  headpiece?: AvatarHeadpiece,
): PixelAvatarRecipe {
  const base = withSpecies(detailedRecipe(DEFAULT_RECIPE), species);
  const v4 =
    headpiece !== undefined ||
    ['strand', 'pattern', 'bangsColor', 'backHairColor', 'strandColor'].some((k) => k in fields);
  const next = { ...(v4 ? withPieces(base) : base), ...fields } as PixelAvatarRecipe;
  return headpiece ? withBuiltInHeadpiece(next, headpiece) : next;
}

/**
 * The BotPixel presets, then one or two for every species BotPixel 0.10 added: elves, dwarves,
 * orcs, goblins, talking flowers and animals, with fur patterns, beards, medieval outfits and
 * headpieces. Site-owned until BotPixel ships presets for them.
 */
export const PRESETS: readonly PixelAvatarRecipe[] = [
  ...AVATAR_PRESETS,
  preset('elf', {
    hair: 'long',
    bangs: 'hime',
    sideHair: 'long',
    rightSideHair: 'long',
    backHair: 'long',
    eyes: 'sharp',
    brows: 'soft',
    mouth: 'smile',
    cheeks: 'none',
    outfit: 'cloak',
    backdrop: 'stars',
    accessory: 'none',
    skinColor: '#fbe7d6',
    hairColor: '#f2dc8a',
    eyeColor: '#4c8a3c',
    shirtColor: '#3d7a4f',
  }),
  preset('dwarf', {
    head: 'square',
    hair: 'crop',
    bangs: 'crop',
    sideHair: 'crop',
    rightSideHair: 'crop',
    backHair: 'none',
    eyes: 'round',
    brows: 'thick',
    mouth: 'grin',
    beard: 'braided',
    outfit: 'armor',
    backdrop: 'sparkles',
    accessory: 'helmet',
    skinColor: '#f2c4a0',
    hairColor: '#c4452f',
    eyeColor: '#5a3a2a',
    shirtColor: '#8a8f98',
  }),
  preset('orc', {
    head: 'square',
    hair: 'mohawk',
    bangs: 'mohawk',
    sideHair: 'none',
    rightSideHair: 'none',
    backHair: 'none',
    eyes: 'sharp',
    brows: 'angry',
    mouth: 'grin',
    outfit: 'tunic',
    backdrop: 'dots',
    accessory: 'earring',
    skinColor: '#6f8a4e',
    hairColor: '#3a3438',
    eyeColor: '#e2b04a',
    shirtColor: '#8a5a36',
  }),
  preset('goblin', {
    hair: 'messy',
    bangs: 'messy',
    sideHair: 'bun',
    rightSideHair: 'bun',
    backHair: 'none',
    eyes: 'happy',
    mouth: 'smirk',
    outfit: 'robe',
    backdrop: 'stars',
    accessory: 'witch',
    skinColor: '#9cc464',
    hairColor: '#6b4fa0',
    eyeColor: '#e2565f',
    shirtColor: '#4a3a6a',
  }),
  preset('flower', {
    eyes: 'round',
    mouth: 'smile',
    cheeks: 'blush',
    petals: 'sunflower',
    flowerBase: 'pot',
    backdrop: 'sparkles',
    skinColor: '#f6d36b',
    hairColor: '#e2b04a',
    eyeColor: '#3a3438',
    shirtColor: '#c98b4a',
  }),
  preset('flower', {
    eyes: 'happy',
    mouth: 'open',
    cheeks: 'blush',
    petals: 'sakura',
    flowerBase: 'leaves',
    backdrop: 'hearts',
    skinColor: '#ffe3cf',
    hairColor: '#f2a0b8',
    eyeColor: '#3a3438',
    shirtColor: '#3d9970',
  }),
  preset('cat', {
    hair: 'crop',
    bangs: 'messy',
    sideHair: 'crop',
    rightSideHair: 'crop',
    backHair: 'none',
    eyes: 'sparkle',
    mouth: 'cat',
    outfit: 'hoodie',
    backdrop: 'dots',
    accessory: 'none',
    pattern: 'tabby',
    strand: 'ahoge',
    skinColor: '#f2a65a',
    hairColor: '#c4452f',
    eyeColor: '#4c8a3c',
    shirtColor: '#3a7ae8',
  }),
  preset('cat', {
    hair: 'bob',
    bangs: 'bob',
    sideHair: 'bob',
    rightSideHair: 'bob',
    backHair: 'bob',
    eyes: 'lashes',
    mouth: 'cat',
    outfit: 'maid',
    backdrop: 'sparkles',
    accessory: 'ribbon',
    pattern: 'colorpoint',
    skinColor: '#f4f1ec',
    hairColor: '#5a3a2a',
    eyeColor: '#3a7ae8',
    shirtColor: '#3a3438',
  }),
  preset('dog', {
    hair: 'curly',
    bangs: 'curly',
    sideHair: 'curly',
    rightSideHair: 'curly',
    backHair: 'none',
    eyes: 'round',
    mouth: 'tongue',
    outfit: 'overalls',
    backdrop: 'hearts',
    accessory: 'cap',
    pattern: 'patches',
    skinColor: '#f4f1ec',
    hairColor: '#8a5a36',
    eyeColor: '#5a3a2a',
    shirtColor: '#e2565f',
  }),
  preset('fox', {
    hair: 'long',
    bangs: 'sweep',
    sideHair: 'long',
    rightSideHair: 'long',
    backHair: 'ponytail',
    eyes: 'sharp',
    mouth: 'smirk',
    outfit: 'kimono',
    backdrop: 'stars',
    accessory: 'flower',
    skinColor: '#e0763a',
    hairColor: '#c4452f',
    eyeColor: '#e2b04a',
    shirtColor: '#f4f1ec',
  }),
  preset('rabbit', {
    hair: 'bob',
    bangs: 'bob',
    sideHair: 'bun',
    rightSideHair: 'bun',
    backHair: 'none',
    eyes: 'round',
    mouth: 'o',
    cheeks: 'blush',
    glasses: 'round',
    outfit: 'cardigan',
    backdrop: 'dots',
    accessory: 'none',
    pattern: 'spots',
    skinColor: '#f4f1ec',
    hairColor: '#d9c7b8',
    eyeColor: '#e2565f',
    shirtColor: '#f2a0b8',
  }),
  preset('bear', {
    head: 'chubby',
    hair: 'crop',
    bangs: 'crop',
    sideHair: 'none',
    rightSideHair: 'none',
    backHair: 'none',
    eyes: 'sleepy',
    mouth: 'smile',
    outfit: 'turtleneck',
    backdrop: 'sparkles',
    accessory: 'beanie',
    skinColor: '#8a5a36',
    hairColor: '#5a3a2a',
    eyeColor: '#3a3438',
    shirtColor: '#e2b04a',
  }),
  preset(
    'human',
    {
      hair: 'wavy',
      bangs: 'wavy',
      sideHair: 'long',
      rightSideHair: 'long',
      backHair: 'wavy',
      eyes: 'sparkle',
      mouth: 'smile',
      outfit: 'dress',
      backdrop: 'stars',
      accessory: 'none',
      skinColor: '#ffe3cf',
      hairColor: '#f4f1ec',
      eyeColor: '#e2b04a',
      shirtColor: '#f4f1ec',
    },
    'halo',
  ),
  preset(
    'human',
    {
      hair: 'twintails',
      bangs: 'bob',
      sideHair: 'bun',
      rightSideHair: 'bun',
      backHair: 'twintails',
      eyes: 'wink',
      mouth: 'tongue',
      outfit: 'sailor',
      backdrop: 'hearts',
      accessory: 'headphones',
      strand: 'double',
      skinColor: '#ffe3cf',
      hairColor: '#3a3438',
      bangsColor: '#e2565f',
      eyeColor: '#e2565f',
      shirtColor: '#3a7ae8',
    },
    'catears',
  ),
  preset('human', {
    head: 'long',
    hair: 'crop',
    bangs: 'sweep',
    sideHair: 'crop',
    rightSideHair: 'crop',
    backHair: 'none',
    eyes: 'sharp',
    brows: 'thick',
    mouth: 'flat',
    beard: 'short',
    outfit: 'armor',
    backdrop: 'none',
    accessory: 'none',
    skinColor: '#c68863',
    hairColor: '#3a3438',
    eyeColor: '#5a3a2a',
    shirtColor: '#8a8f98',
  }),
  preset(
    'human',
    {
      hair: 'long',
      bangs: 'hime',
      sideHair: 'hime',
      rightSideHair: 'hime',
      backHair: 'long',
      eyes: 'lashes',
      mouth: 'smile',
      outfit: 'robe',
      backdrop: 'sparkles',
      accessory: 'none',
      skinColor: '#ffe3cf',
      hairColor: '#4468d0',
      eyeColor: '#d9c7e8',
      shirtColor: '#6b4fa0',
    },
    'wings',
  ),
];
